apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apache-app
  description: An example of a Backstage application.
  annotations:
    argocd/app-name: apache-app
spec:
  type: service
  owner: user:guest  
  lifecycle: production

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
  description: An example of a Backstage application.
  annotations:
    argocd/app-name: my-app
    backstage.io/kubernetes-id: my-app-service
spec:
  type: service
  owner: user:guest  
  lifecycle: production
