apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-apache-app-test
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    argocd/app-name: apache-app
spec:
  type: service
  owner: user:guest  
  lifecycle: production
